# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 Yasuhiro / AIseed

"""Shared figure footer.

Every figure rendered or exported by this app carries a footer with data
provenance and the app identifier. Implemented once here so views never
forget it. See `figure-export` and `aiseed-conventions` skills.
"""

from __future__ import annotations

from datetime import datetime, timezone

from matplotlib.figure import Figure


def apply_footer(
    fig: Figure,
    *,
    data_source: str,
    run_id: str,
    license_text: str = "CC-BY-4.0",
) -> None:
    timestamp = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M")
    text = (
        f"Data: {data_source} (run {run_id}). {license_text}\n"
        f"Generated by AIseed Weather v0.1 (https://aiseed.dev) — "
        f"{timestamp} UTC"
    )
    fig.text(
        0.99, 0.01, text,
        ha="right", va="bottom",
        fontsize=7, color="#555555", family="sans-serif",
    )
