# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 Yasuhiro / AIseed

"""Shared figure footer.

Every figure rendered or exported by this app carries a footer with data
provenance and the app identifier. Implemented once here so views never
forget it. See `figure-export` and `aiseed-conventions` skills.
"""

from __future__ import annotations

from datetime import datetime, timezone

from matplotlib.figure import Figure
from matplotlib.text import Text


def apply_footer(
    fig: Figure,
    *,
    data_source: str,
    run_id: str,
    license_text: str = "CC-BY-4.0",
    run_label: str = "run",
) -> Text:
    """Add the provenance footer and return the Text artist.

    Returning the artist lets callers that recycle the Figure across
    frames remove() the footer before the next render — the basemap
    cache pattern relies on this so each frame's footer (with its own
    run_id and timestamp) doesn't pile up.

    ``run_label`` names what ``run_id`` identifies: a model run for
    forecasts, the observed period for observation records.
    """
    timestamp = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M")
    text = (
        f"Data: {data_source} ({run_label} {run_id}). {license_text}\n"
        f"Generated by AIseed Weather v0.1 (https://aiseed.dev) — "
        f"{timestamp} UTC"
    )
    return fig.text(
        0.99, 0.01, text,
        ha="right", va="bottom",
        # No font family here: the app-wide default (figures/_fonts.py)
        # carries CJK glyphs, which JMA attribution needs.
        fontsize=7, color="#555555",
    )
